server:
  port: 8001


spring:
  datasource:
    username: root
    password: chenjiajun1999
    url: jdbc:mysql://127.0.0.1:3306/shortlink?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: select 1
      connection-timeout: 20000
      idle-timeout: 300000
      maximum-pool-size: 5
      minimum-idle: 5

  data:
    redis:
      host: 127.0.0.1
      port: 6379
